"""Generate a HuggingFace model card (model_card.md) for the fine-tuned model."""

from __future__ import annotations

import json
from pathlib import Path

from touster.config import RecipeConfig
from touster import display


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_best_bpb(run_dir: Path) -> float | None:
    """Read best_bpb from run.json if it exists."""
    run_json = run_dir / "run.json"
    if not run_json.exists():
        return None
    try:
        data = json.loads(run_json.read_text(encoding="utf-8"))
        bpb = data.get("best_bpb")
        if bpb is not None and bpb != float("inf"):
            return float(bpb)
    except Exception:  # noqa: BLE001
        pass
    return None


def _load_dataset_size(run_dir: Path) -> int | None:
    """Count samples in experiments.jsonl as a proxy for dataset activity."""
    jsonl = run_dir / "experiments.jsonl"
    if not jsonl.exists():
        return None
    try:
        lines = [ln for ln in jsonl.read_text(encoding="utf-8").splitlines() if ln.strip()]
        return len(lines)
    except Exception:  # noqa: BLE001
        return None


def _build_usage_snippet(recipe: RecipeConfig) -> str:
    return f"""\
```python
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import PeftModel

base_model = "{recipe.base_model}"
adapter_path = "./final_adapter"  # or path to merged_weights

tokenizer = AutoTokenizer.from_pretrained(base_model)
base = AutoModelForCausalLM.from_pretrained(base_model)
model = PeftModel.from_pretrained(base, adapter_path)
model.eval()

inputs = tokenizer("Hello, world!", return_tensors="pt")
output = model.generate(**inputs, max_new_tokens=64)
print(tokenizer.decode(output[0], skip_special_tokens=True))
```"""


def _build_card(
    recipe: RecipeConfig,
    run_dir: Path,
    best_bpb: float | None,
    dataset_size: int | None,
    repo_id: str,
) -> str:
    """Build the full model card markdown string."""
    target_mods = ", ".join(f"`{m}`" for m in recipe.target_modules)

    hub_section = ""
    if repo_id:
        hub_section = f"\n**HuggingFace Hub:** [{repo_id}](https://huggingface.co/{repo_id})\n"

    bpb_section = ""
    if best_bpb is not None:
        bpb_section = f"\n**Best eval BPB:** `{best_bpb:.4f}`\n"

    dataset_section = ""
    if dataset_size is not None:
        dataset_section = f"\n**Experiments logged:** {dataset_size}\n"

    return f"""\
---
tags:
  - lora
  - fine-tuning
  - touster
base_model: {recipe.base_model}
---

# Fine-Tuned Model

{hub_section}

## Model Description

This model is a LoRA fine-tuned version of [{recipe.base_model}](https://huggingface.co/{recipe.base_model}).

| Property | Value |
|---|---|
| Base model | `{recipe.base_model}` |
| LoRA rank | `{recipe.lora_rank}` |
| LoRA alpha | `{recipe.lora_alpha}` |
| Target modules | {target_mods} |

## Training Details

| Hyperparameter | Value |
|---|---|
| learning_rate | `{recipe.learning_rate}` |
| lora_rank | `{recipe.lora_rank}` |
| lora_alpha | `{recipe.lora_alpha}` |
| scheduler | `{recipe.scheduler}` |
| warmup_steps | `{recipe.warmup_steps}` |
| num_epochs | `{recipe.num_epochs}` |
| max_steps | `{recipe.max_steps}` |
| batch_size | `{recipe.batch_size}` |
| gradient_accumulation_steps | `{recipe.gradient_accumulation_steps}` |

## Dataset Info
{dataset_section}
Training data was processed and deduplicated by [Touster](https://github.com/touster).
Run directory: `{run_dir.as_posix()}`

## Evaluation
{bpb_section}
BPB = bits-per-byte on the held-out evaluation split.

## Usage

{_build_usage_snippet(recipe)}

---

*Generated by [Touster](https://github.com/touster) — an all-in-one LoRA fine-tuning pipeline.*
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_model_card(
    recipe: RecipeConfig,
    run_dir: Path,
    push_to_hub: bool = False,
    repo_id: str = "",
) -> Path:
    """
    Generate model_card.md in run_dir.

    Content sections:
    - Model description (base model, LoRA config)
    - Training details (from RecipeConfig: lr, rank, alpha, scheduler)
    - Dataset info (dataset size from experiments.jsonl if available)
    - Best eval bpb from run.json if available
    - Usage example (Python snippet using transformers + PEFT)
    - "Generated by Touster" footer

    If push_to_hub=True and repo_id is set: push to HF Hub using huggingface_hub.
    Otherwise just save locally.

    Returns path to model_card.md.
    """
    run_dir.mkdir(parents=True, exist_ok=True)

    best_bpb = _load_best_bpb(run_dir)
    dataset_size = _load_dataset_size(run_dir)

    print("Generating model card...")
    card_text = _build_card(
        recipe=recipe,
        run_dir=run_dir,
        best_bpb=best_bpb,
        dataset_size=dataset_size,
        repo_id=repo_id,
    )

    card_path = run_dir / "model_card.md"
    card_path.write_text(card_text, encoding="utf-8")
    display.success(f"Model card written: {card_path}")

    if push_to_hub and repo_id:
        _push_to_hub(card_path, repo_id)

    return card_path


def _push_to_hub(card_path: Path, repo_id: str) -> None:
    """Push model card to HuggingFace Hub."""
    try:
        from huggingface_hub import HfApi

        api = HfApi()
        print(f"Pushing model card to Hub: {repo_id}")
        api.upload_file(
            path_or_fileobj=str(card_path),
            path_in_repo="README.md",
            repo_id=repo_id,
            repo_type="model",
        )
        display.success(f"Model card pushed to Hub: https://huggingface.co/{repo_id}")
    except ImportError:
        display.warning("huggingface_hub not installed — skipping Hub push.")
    except Exception as exc:  # noqa: BLE001
        display.warning(f"Hub push failed: {exc}")
